-- ConfirmaEdu — banco completo para Supabase
-- Execute este arquivo inteiro uma única vez no SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.school_today()
returns date
language sql
stable
as $$
  select (now() at time zone 'America/Fortaleza')::date;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(full_name) between 3 and 120),
  registration text not null unique check (registration ~ '^[a-z0-9._-]{3,30}$'),
  classroom text,
  role text not null default 'student' check (role in ('student', 'canteen', 'direction', 'pending')),
  requested_role text not null default 'student' check (requested_role in ('student', 'canteen', 'direction')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id)
);

create table if not exists public.meal_confirmations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  meal_date date not null default public.school_today(),
  will_eat boolean not null,
  updated_at timestamptz not null default now(),
  unique (user_id, meal_date)
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  meal_date date not null default public.school_today(),
  checked_in_at timestamptz not null default now(),
  method text not null default 'qr' check (method in ('qr', 'manual')),
  registered_by uuid references public.profiles(id),
  unique (user_id, meal_date)
);

create table if not exists public.weekly_menu (
  id bigint generated by default as identity primary key,
  menu_date date not null unique,
  main_dish text not null,
  sides text,
  dessert text,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id)
);

create table if not exists public.justifications (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  absence_date date not null,
  reason text not null check (char_length(reason) between 3 and 1000),
  file_path text not null,
  file_name text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (student_id, absence_date)
);

create table if not exists public.qr_sessions (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  meal_date date not null unique default public.school_today(),
  active boolean not null default true,
  expires_at timestamptz not null,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists meal_confirmations_date_idx on public.meal_confirmations(meal_date);
create index if not exists attendance_date_idx on public.attendance(meal_date);
create index if not exists justifications_status_idx on public.justifications(status);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested text;
  assigned text;
  registration_value text;
begin
  requested := coalesce(new.raw_user_meta_data ->> 'requested_role', 'student');
  if requested not in ('student', 'canteen', 'direction') then
    requested := 'student';
  end if;

  assigned := case when requested = 'student' then 'student' else 'pending' end;
  registration_value := lower(coalesce(new.raw_user_meta_data ->> 'registration', ''));

  if registration_value !~ '^[a-z0-9._-]{3,30}$' then
    raise exception 'Identificador inválido.';
  end if;

  insert into public.profiles (id, full_name, registration, classroom, role, requested_role)
  values (
    new.id,
    trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')),
    registration_value,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'classroom', '')), ''),
    assigned,
    requested
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.bootstrap_first_direction()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  caller public.profiles%rowtype;
begin
  select * into caller from public.profiles where id = auth.uid();

  if caller.id is null or caller.role <> 'pending' or caller.requested_role <> 'direction' then
    return false;
  end if;

  if exists (select 1 from public.profiles where role = 'direction') then
    return false;
  end if;

  update public.profiles
  set role = 'direction', approved_at = now(), approved_by = id
  where id = auth.uid();

  return true;
end;
$$;

create or replace function public.approve_staff(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() <> 'direction' then
    raise exception 'Somente a direção pode liberar acessos.';
  end if;

  if p_role not in ('canteen', 'direction') then
    raise exception 'Tipo de acesso inválido.';
  end if;

  update public.profiles
  set role = p_role, approved_at = now(), approved_by = auth.uid()
  where id = p_user_id and role = 'pending';

  if not found then
    raise exception 'Solicitação não encontrada.';
  end if;
end;
$$;

create or replace function public.generate_daily_qr()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  qr_token uuid;
  today_date date := public.school_today();
  day_end timestamptz := ((public.school_today() + 1)::timestamp at time zone 'America/Fortaleza');
begin
  if public.current_app_role() not in ('canteen', 'direction') then
    raise exception 'Acesso não autorizado.';
  end if;

  select token into qr_token
  from public.qr_sessions
  where meal_date = today_date and active = true and expires_at > now();

  if qr_token is null then
    insert into public.qr_sessions (meal_date, expires_at, created_by)
    values (today_date, day_end, auth.uid())
    on conflict (meal_date) do update
      set token = gen_random_uuid(), active = true, expires_at = excluded.expires_at,
          created_by = auth.uid(), created_at = now()
    returning token into qr_token;
  end if;

  return qr_token::text;
end;
$$;

create or replace function public.register_qr_attendance(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  record_time timestamptz;
begin
  if public.current_app_role() <> 'student' then
    raise exception 'Somente alunos registram presença pelo QR Code.';
  end if;

  if not exists (
    select 1 from public.qr_sessions
    where token::text = p_token
      and meal_date = public.school_today()
      and active = true
      and expires_at > now()
  ) then
    raise exception 'QR Code inválido ou expirado.';
  end if;

  insert into public.attendance (user_id, meal_date, method)
  values (auth.uid(), public.school_today(), 'qr')
  on conflict (user_id, meal_date) do nothing;

  insert into public.meal_confirmations (user_id, meal_date, will_eat, updated_at)
  values (auth.uid(), public.school_today(), true, now())
  on conflict (user_id, meal_date) do update
    set will_eat = true, updated_at = now();

  select checked_in_at into record_time
  from public.attendance
  where user_id = auth.uid() and meal_date = public.school_today();

  return jsonb_build_object('checked_in_at', record_time);
end;
$$;

create or replace function public.register_manual_attendance(p_registration text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  student_id uuid;
  student_name text;
  record_time timestamptz;
begin
  if public.current_app_role() not in ('canteen', 'direction') then
    raise exception 'Acesso não autorizado.';
  end if;

  select id, full_name into student_id, student_name
  from public.profiles
  where registration = lower(trim(p_registration)) and role = 'student';

  if student_id is null then
    raise exception 'Matrícula não encontrada.';
  end if;

  insert into public.attendance (user_id, meal_date, method, registered_by)
  values (student_id, public.school_today(), 'manual', auth.uid())
  on conflict (user_id, meal_date) do update
    set method = 'manual', registered_by = auth.uid();

  insert into public.meal_confirmations (user_id, meal_date, will_eat, updated_at)
  values (student_id, public.school_today(), true, now())
  on conflict (user_id, meal_date) do update
    set will_eat = true, updated_at = now();

  select checked_in_at into record_time
  from public.attendance
  where user_id = student_id and meal_date = public.school_today();

  return jsonb_build_object('student', student_name, 'checked_in_at', record_time);
end;
$$;

create or replace function public.review_justification(p_justification_id uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() <> 'direction' then
    raise exception 'Somente a direção pode analisar justificativas.';
  end if;

  if p_status not in ('approved', 'rejected') then
    raise exception 'Situação inválida.';
  end if;

  update public.justifications
  set status = p_status, reviewed_by = auth.uid(), reviewed_at = now()
  where id = p_justification_id;

  if not found then
    raise exception 'Justificativa não encontrada.';
  end if;
end;
$$;

alter table public.profiles enable row level security;
alter table public.meal_confirmations enable row level security;
alter table public.attendance enable row level security;
alter table public.weekly_menu enable row level security;
alter table public.justifications enable row level security;
alter table public.qr_sessions enable row level security;

drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles for select to authenticated
using (
  id = auth.uid()
  or public.current_app_role() = 'direction'
  or (public.current_app_role() = 'canteen' and role = 'student')
);

drop policy if exists "confirmations_select" on public.meal_confirmations;
create policy "confirmations_select" on public.meal_confirmations for select to authenticated
using (user_id = auth.uid() or public.current_app_role() in ('canteen', 'direction'));

drop policy if exists "confirmations_insert" on public.meal_confirmations;
create policy "confirmations_insert" on public.meal_confirmations for insert to authenticated
with check (
  user_id = auth.uid()
  and public.current_app_role() = 'student'
  and meal_date = public.school_today()
);

drop policy if exists "confirmations_update" on public.meal_confirmations;
create policy "confirmations_update" on public.meal_confirmations for update to authenticated
using (user_id = auth.uid() and public.current_app_role() = 'student')
with check (
  user_id = auth.uid()
  and public.current_app_role() = 'student'
  and meal_date = public.school_today()
);

drop policy if exists "attendance_select" on public.attendance;
create policy "attendance_select" on public.attendance for select to authenticated
using (user_id = auth.uid() or public.current_app_role() in ('canteen', 'direction'));

drop policy if exists "menu_select" on public.weekly_menu;
create policy "menu_select" on public.weekly_menu for select to authenticated using (true);

drop policy if exists "menu_insert" on public.weekly_menu;
create policy "menu_insert" on public.weekly_menu for insert to authenticated
with check (public.current_app_role() in ('canteen', 'direction'));

drop policy if exists "menu_update" on public.weekly_menu;
create policy "menu_update" on public.weekly_menu for update to authenticated
using (public.current_app_role() in ('canteen', 'direction'))
with check (public.current_app_role() in ('canteen', 'direction'));

drop policy if exists "justifications_select" on public.justifications;
create policy "justifications_select" on public.justifications for select to authenticated
using (student_id = auth.uid() or public.current_app_role() = 'direction');

drop policy if exists "justifications_insert" on public.justifications;
create policy "justifications_insert" on public.justifications for insert to authenticated
with check (student_id = auth.uid() and public.current_app_role() = 'student');

drop policy if exists "qr_select_staff" on public.qr_sessions;
create policy "qr_select_staff" on public.qr_sessions for select to authenticated
using (public.current_app_role() in ('canteen', 'direction'));

revoke all on public.profiles, public.meal_confirmations, public.attendance,
  public.weekly_menu, public.justifications, public.qr_sessions from anon;

grant select on public.profiles to authenticated;
grant select, insert, update on public.meal_confirmations to authenticated;
grant select on public.attendance to authenticated;
grant select, insert, update on public.weekly_menu to authenticated;
grant select, insert on public.justifications to authenticated;
grant select on public.qr_sessions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.bootstrap_first_direction() from public;
revoke all on function public.approve_staff(uuid, text) from public;
revoke all on function public.generate_daily_qr() from public;
revoke all on function public.register_qr_attendance(text) from public;
revoke all on function public.register_manual_attendance(text) from public;
revoke all on function public.review_justification(uuid, text) from public;

grant execute on function public.bootstrap_first_direction() to authenticated;
grant execute on function public.approve_staff(uuid, text) to authenticated;
grant execute on function public.generate_daily_qr() to authenticated;
grant execute on function public.register_qr_attendance(text) to authenticated;
grant execute on function public.register_manual_attendance(text) to authenticated;
grant execute on function public.review_justification(uuid, text) to authenticated;

insert into storage.buckets (id, name, public)
values ('justifications', 'justifications', false)
on conflict (id) do update set public = false;

drop policy if exists "student_upload_justification" on storage.objects;
create policy "student_upload_justification" on storage.objects for insert to authenticated
with check (
  bucket_id = 'justifications'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.current_app_role() = 'student'
);

drop policy if exists "read_justification_files" on storage.objects;
create policy "read_justification_files" on storage.objects for select to authenticated
using (
  bucket_id = 'justifications'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.current_app_role() = 'direction'
  )
);

drop policy if exists "student_delete_own_justification" on storage.objects;
create policy "student_delete_own_justification" on storage.objects for delete to authenticated
using (
  bucket_id = 'justifications'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.current_app_role() = 'student'
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array['profiles', 'meal_confirmations', 'attendance', 'weekly_menu', 'justifications', 'qr_sessions']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end;
$$;

-- Tudo pronto. Agora desative a confirmação de e-mail no painel de Authentication
-- e preencha apenas SUPABASE_URL e SUPABASE_KEY no arquivo config.js.
